#ifndef DMINI_H
#define DMINI_H

#include "dmod.h"
#include "dmini_defs.h"  // Generated by CMake from DMOD's api.h.in template

/**
 * @brief DMINI - DMOD INI File Parser Module
 * 
 * This module provides an API for parsing and generating INI files.
 * It uses only SAL (System Abstraction Layer) functions from DMOD.
 * 
 * INI file format:
 * - Sections are defined by [section_name]
 * - Key-value pairs are defined by key=value
 * - Comments start with ; or #
 * - Whitespace is trimmed from keys and values
 */

/**
 * @brief Error codes
 */
#define DMINI_OK                0
#define DMINI_ERR_GENERAL      -1
#define DMINI_ERR_MEMORY       -2
#define DMINI_ERR_INVALID      -3
#define DMINI_ERR_NOT_FOUND    -4
#define DMINI_ERR_FILE         -5
#define DMINI_ERR_LOCKED       -6

/**
 * @brief INI context type (opaque)
 * 
 * This is an opaque pointer to the INI file context structure.
 */
typedef struct dmini_context* dmini_context_t;

/**
 * @brief Initialize INI context
 * 
 * Creates a new INI context for storing sections and key-value pairs.
 * 
 * @return Pointer to INI context or NULL on error
 */
dmod_dmini_api(1.0, dmini_context_t, _create, (void));

/**
 * @brief Free INI context
 * 
 * Frees all memory associated with the INI context.
 * 
 * @param ctx INI context to free
 */
dmod_dmini_api(1.0, void, _destroy, (dmini_context_t ctx));

/**
 * @brief Parse INI file from string
 * 
 * Parses an INI file from a null-terminated string.
 * 
 * @param ctx INI context
 * @param data String containing INI file contents
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _parse_string, (dmini_context_t ctx, const char* data));

/**
 * @brief Parse INI file
 * 
 * Parses an INI file from a file path using SAL file functions.
 * 
 * @param ctx INI context
 * @param filename Path to INI file
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _parse_file, (dmini_context_t ctx, const char* filename));

/**
 * @brief Generate INI file to string
 * 
 * Generates an INI file string from the context.
 * If buffer is NULL, returns the required buffer size.
 * If buffer is not NULL, fills it with the INI data.
 * 
 * @param ctx INI context
 * @param buffer Buffer to write to (NULL to query size)
 * @param buffer_size Size of the buffer
 * @return Required buffer size, or negative error code
 */
dmod_dmini_api(1.0, int, _generate_string, (dmini_context_t ctx, char* buffer, size_t buffer_size));

/**
 * @brief Generate INI file
 * 
 * Generates an INI file from the context and writes it to a file.
 * 
 * @param ctx INI context
 * @param filename Path to output INI file
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _generate_file, (dmini_context_t ctx, const char* filename));

/**
 * @brief Get string value from INI context
 * 
 * Retrieves a string value for the given section and key.
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @param default_value Default value if key not found
 * @return Value string or default_value if not found
 */
dmod_dmini_api(1.0, const char*, _get_string, (dmini_context_t ctx, 
                                                const char* section, 
                                                const char* key, 
                                                const char* default_value));

/**
 * @brief Get integer value from INI context
 * 
 * Retrieves an integer value for the given section and key.
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @param default_value Default value if key not found
 * @return Integer value or default_value if not found
 */
dmod_dmini_api(1.0, int, _get_int, (dmini_context_t ctx, 
                                     const char* section, 
                                     const char* key, 
                                     int default_value));

/**
 * @brief Set string value in INI context
 * 
 * Sets a string value for the given section and key.
 * Creates the section if it doesn't exist.
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @param value Value string
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _set_string, (dmini_context_t ctx, 
                                        const char* section, 
                                        const char* key, 
                                        const char* value));

/**
 * @brief Set integer value in INI context
 * 
 * Sets an integer value for the given section and key.
 * Creates the section if it doesn't exist.
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @param value Integer value
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _set_int, (dmini_context_t ctx, 
                                     const char* section, 
                                     const char* key, 
                                     int value));

/**
 * @brief Check if section exists
 * 
 * @param ctx INI context
 * @param section Section name
 * @return 1 if section exists, 0 otherwise
 */
dmod_dmini_api(1.0, int, _has_section, (dmini_context_t ctx, const char* section));

/**
 * @brief Check if key exists in section
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @return 1 if key exists, 0 otherwise
 */
dmod_dmini_api(1.0, int, _has_key, (dmini_context_t ctx, 
                                     const char* section, 
                                     const char* key));

/**
 * @brief Remove section from INI context
 * 
 * @param ctx INI context
 * @param section Section name
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _remove_section, (dmini_context_t ctx, const char* section));

/**
 * @brief Remove key from section
 * 
 * @param ctx INI context
 * @param section Section name (NULL for global section)
 * @param key Key name
 * @return DMINI_OK on success, error code on failure
 */
dmod_dmini_api(1.0, int, _remove_key, (dmini_context_t ctx, 
                                        const char* section, 
                                        const char* key));

/**
 * @brief Get number of sections in the context
 *
 * Returns the total number of sections, including the global (unnamed) section.
 * Respects the active-section restriction when it is in effect.
 *
 * @param ctx INI context
 * @return Number of sections, or DMINI_ERR_INVALID if ctx is NULL
 */
dmod_dmini_api(1.0, int, _section_count, (dmini_context_t ctx));

/**
 * @brief Get section name at the given index
 *
 * Returns the name of the section at position @p index (0-based).
 * The global (unnamed) section is represented by NULL.
 * Respects the active-section restriction when it is in effect.
 * Use dmini_section_count() to determine the valid index range.
 *
 * @param ctx   INI context
 * @param index Zero-based section index
 * @return Section name, NULL for the global section, or NULL if index is out of range
 */
dmod_dmini_api(1.0, const char*, _section_name, (dmini_context_t ctx, int index));

/**
 * @brief Get number of keys in a section
 *
 * Returns the number of key-value pairs in the given section.
 * Respects the active-section restriction when it is in effect.
 *
 * @param ctx     INI context
 * @param section Section name (NULL for global section)
 * @return Number of keys, or DMINI_ERR_INVALID if ctx is NULL,
 *         or DMINI_ERR_NOT_FOUND if section does not exist
 */
dmod_dmini_api(1.0, int, _key_count, (dmini_context_t ctx, const char* section));

/**
 * @brief Get key name at the given index within a section
 *
 * Returns the name of the key at position @p index (0-based) within @p section.
 * Use dmini_key_count() to determine the valid index range.
 * Respects the active-section restriction when it is in effect.
 *
 * @param ctx     INI context
 * @param section Section name (NULL for global section)
 * @param index   Zero-based key index
 * @return Key name, or NULL if index is out of range or section not found
 */
dmod_dmini_api(1.0, const char*, _key_name, (dmini_context_t ctx,
                                              const char* section,
                                              int index));

/**
 * @brief Initialize INI context with owner token
 *
 * Creates a new INI context protected by a magic number token.
 * The token must be supplied to dmini_set_active_section and
 * dmini_clear_active_section when a non-zero token is used.
 * Using token value 0 is equivalent to calling dmini_create().
 *
 * @param owner_token Magic number that guards active-section changes (0 = unprotected)
 * @return Pointer to INI context or NULL on error
 */
dmod_dmini_api(1.0, dmini_context_t, _create_with_token, (unsigned int owner_token));

/**
 * @brief Set the active section restriction
 *
 * Restricts the context so that only the named section is visible to
 * consumers of this context.  While the restriction is active all API
 * calls treat section == NULL as a reference to the active section, and
 * any attempt to access a different section returns not-found / default.
 * Pass NULL as section to restrict to the global (unnamed) section.
 *
 * @param ctx        INI context
 * @param section    Section to make active (NULL for global section)
 * @param owner_token Magic number that was supplied to dmini_create_with_token
 *                    (ignored when the context was created with token 0)
 * @return DMINI_OK on success, DMINI_ERR_LOCKED if the token is wrong,
 *         DMINI_ERR_INVALID if ctx is NULL
 */
dmod_dmini_api(1.0, int, _set_active_section, (dmini_context_t ctx,
                                                const char* section,
                                                unsigned int owner_token));

/**
 * @brief Clear the active section restriction
 *
 * Removes the active-section restriction so that the full content of the
 * context becomes visible again.
 *
 * @param ctx        INI context
 * @param owner_token Magic number that was supplied to dmini_create_with_token
 *                    (ignored when the context was created with token 0)
 * @return DMINI_OK on success, DMINI_ERR_LOCKED if the token is wrong,
 *         DMINI_ERR_INVALID if ctx is NULL
 */
dmod_dmini_api(1.0, int, _clear_active_section, (dmini_context_t ctx,
                                                  unsigned int owner_token));

#endif // DMINI_H
